// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function GetRenderedHTML() {
  return window['go']['main']['App']['GetRenderedHTML']();
}

export function GetTOC() {
  return window['go']['main']['App']['GetTOC']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
