// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentFile():Promise<Record<string, any>>;

export function GetFilePath():Promise<string>;

export function GetRenderedHTML():Promise<string>;

export function GetTOC():Promise<Array<Record<string, any>>>;

export function OpenFile(arg1:string):Promise<void>;

export function Ready():Promise<void>;

export function Refresh():Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
